language: clojure
lein: lein
script: "! lein cljsbuild once 2>&1 | grep WARNING:"
jdk:
- oraclejdk8
notifications:
  irc: "chat.freenode.net#lighttable"
  email:
  - gabriel.horner@gmail.com
  - kenny.evitt@gmail.com
  - mrundberget@hotmail.com
